apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-secrets
  namespace: ecommerce
type: Opaque
data:
  # Base64 encoded values (replace with actual values)
  SECRET_KEY: eW91ci1zZWNyZXQta2V5
  DATABASE_URL: cG9zdGdyZXNxbDovL3VzZXI6cGFzc3dvcmRAcG9zdGdyZXM6NTQzMi9lY29tbWVyY2U=
  REDIS_URL: cmVkaXM6Ly9yZWRpczo2Mzc5LzA=
  AFRICAS_TALKING_API_KEY: YXN0a3NfMjI3N2M4YWVmMTE4MGM3OTYzNWE3NTUxYTVaNTJiYjVmYTJkNjYwZjRkNDdhN2E2OTlkNTEwZDBiMDEwZGQ1Y2I2Yjg3MDM1OWI=
  EMAIL_HOST_USER: eW91ci1lbWFpbEBleGFtcGxlLmNvbQ==
  EMAIL_HOST_PASSWORD: eW91ci1lbWFpbC1wYXNzd29yZA==
