apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-secrets
  namespace: ecommerce
type: Opaque
data:
  # Base64 encoded values (replace with actual values)
  SECRET_KEY: <base64-encoded-secret-key>
  DATABASE_URL: <base64-encoded-database-url>
  REDIS_URL: <base64-encoded-redis-url>
  AFRICAS_TALKING_API_KEY: <base64-encoded-api-key>
  EMAIL_HOST_USER: <base64-encoded-email>
  EMAIL_HOST_PASSWORD: <base64-encoded-password>
