apiVersion: v1
kind: Service
metadata:
  name: ecommerce-api-service
  namespace: ecommerce
spec:
  selector:
    app: ecommerce-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
  stringData:
    DATABASE_URL: "postgresql://postgres:e-commerce@db.tslmzgiathzolqfolvpj.supabase.co:5432/postgres"
    SECRET_KEY: "your-django-secret-key"
    REDIS_URL: "redis://redis:6379/0"
